In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [2]:
revenues

NameError: name 'revenues' is not defined

In [3]:
revenue

[14574.49,
 7606.46,
 8611.41,
 9175.41,
 8058.65,
 8105.44,
 11496.28,
 9766.09,
 10305.32,
 14379.96,
 10713.97,
 15433.5]

In [4]:
expenses

[12051.82,
 5695.07,
 12319.2,
 12089.72,
 8658.57,
 840.2,
 3285.73,
 5821.12,
 6976.93,
 16618.61,
 10054.37,
 3803.96]

In [5]:
type(revenue)

list

In [6]:
type(expenses)

list

In [7]:
for i, j in revenue:
    print(i+j)

TypeError: cannot unpack non-iterable float object

In [8]:
for i in revenue:
    print(i)

14574.49
7606.46
8611.41
9175.41
8058.65
8105.44
11496.28
9766.09
10305.32
14379.96
10713.97
15433.5


In [9]:
import numpy as np

In [11]:
rev_array = np.array(revenue)
exp_array = np.array(expenses)

In [12]:
type(rev_array)

numpy.ndarray

In [13]:
profit_pm = rev_array - exp_array
profit_pm

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [14]:
pat_pm = profit_pm * 0.7
pat_pm

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [15]:
pmargin_pm = pat_pm/rev_array
pmargin_pm

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [17]:
good_months = pat_pm[pat_pm > np.mean(pat_pm)]
good_months

array([1765.869, 5085.668, 5747.385, 2761.479, 2329.873, 8140.678])

In [18]:
bad_months = pat_pm[pat_pm < np.mean(pat_pm)]
bad_months

array([ 1337.973, -2595.453, -2040.017,  -419.944, -1567.055,   461.72 ])

In [19]:
best_month = np.max(pat_pm)
best_month

8140.678

In [20]:
worst_month = np.min(pat_pm)
worst_month

-2595.4530000000004

In [22]:
print(profit_pm)
print(pat_pm)
print(pmargin_pm)
print(good_months)
print(bad_months)
print(best_month)
print(worst_month)

[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]
[ 1765.869  1337.973 -2595.453 -2040.017  -419.944  5085.668  5747.385
  2761.479  2329.873 -1567.055   461.72   8140.678]
[ 0.12116163  0.17589956 -0.30139698 -0.22233524 -0.05211096  0.62743886
  0.49993433  0.28276199  0.22608449 -0.10897492  0.04309514  0.52746804]
[1765.869 5085.668 5747.385 2761.479 2329.873 8140.678]
[ 1337.973 -2595.453 -2040.017  -419.944 -1567.055   461.72 ]
8140.678
-2595.4530000000004
